App\Entity\Comment:
    type: entity
    repositoryClass: App\Repository\CommentRepository

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
            options:
                unsigned: true
    fields:
        comment: ~

    manyToOne:
        user:
            targetEntity: User
            inversedBy: comments
            joinColumn:
                nullable: false
